//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace wcf_Master
{
    using System.Runtime.Serialization;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.Runtime.Serialization.DataContractAttribute(Name="login_authentication", Namespace="http://schemas.datacontract.org/2004/07/BridgeWCF.Library")]
    public partial class login_authentication : object
    {
        
        private int activeField;
        
        private string address_cityField;
        
        private string address_countryField;
        
        private string address_stateField;
        
        private string address_streetField;
        
        private string address_zipcodeField;
        
        private string answer1Field;
        
        private string answer2Field;
        
        private int approvedField;
        
        private string birth_placeField;
        
        private string birthdayField;
        
        private string bp_statusField;
        
        private int civil_status_idField;
        
        private int company_idField;
        
        private int created_byField;
        
        private string date_createdField;
        
        private string display_nameField;
        
        private string email_addressField;
        
        private string enc_keyField;
        
        private string facebookField;
        
        private string first_nameField;
        
        private string full_nameField;
        
        private int gender_idField;
        
        private string heightField;
        
        private string image_pathField;
        
        private string instagramField;
        
        private string last_nameField;
        
        private string linkedinField;
        
        private string middle_nameField;
        
        private int nationality_idField;
        
        private string nick_nameField;
        
        private string perm_cityField;
        
        private string perm_countryField;
        
        private string perm_stateField;
        
        private string perm_streetField;
        
        private string perm_zipcodeField;
        
        private string phone_faxField;
        
        private string phone_homeField;
        
        private string phone_mobileField;
        
        private string phone_otherField;
        
        private string phone_workField;
        
        private int question1Field;
        
        private int question2Field;
        
        private int religion_idField;
        
        private int salutation_idField;
        
        private string skypeField;
        
        private string tumblrField;
        
        private string twitterField;
        
        private string user_codeField;
        
        private int user_group_idField;
        
        private int user_idField;
        
        private string userhashField;
        
        private string usernameField;
        
        private int warehouse_idField;
        
        private string websiteField;
        
        private string weightField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int active
        {
            get
            {
                return this.activeField;
            }
            set
            {
                this.activeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string address_city
        {
            get
            {
                return this.address_cityField;
            }
            set
            {
                this.address_cityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string address_country
        {
            get
            {
                return this.address_countryField;
            }
            set
            {
                this.address_countryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string address_state
        {
            get
            {
                return this.address_stateField;
            }
            set
            {
                this.address_stateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string address_street
        {
            get
            {
                return this.address_streetField;
            }
            set
            {
                this.address_streetField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string address_zipcode
        {
            get
            {
                return this.address_zipcodeField;
            }
            set
            {
                this.address_zipcodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string answer1
        {
            get
            {
                return this.answer1Field;
            }
            set
            {
                this.answer1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string answer2
        {
            get
            {
                return this.answer2Field;
            }
            set
            {
                this.answer2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int approved
        {
            get
            {
                return this.approvedField;
            }
            set
            {
                this.approvedField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string birth_place
        {
            get
            {
                return this.birth_placeField;
            }
            set
            {
                this.birth_placeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string birthday
        {
            get
            {
                return this.birthdayField;
            }
            set
            {
                this.birthdayField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string bp_status
        {
            get
            {
                return this.bp_statusField;
            }
            set
            {
                this.bp_statusField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int civil_status_id
        {
            get
            {
                return this.civil_status_idField;
            }
            set
            {
                this.civil_status_idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int company_id
        {
            get
            {
                return this.company_idField;
            }
            set
            {
                this.company_idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int created_by
        {
            get
            {
                return this.created_byField;
            }
            set
            {
                this.created_byField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string date_created
        {
            get
            {
                return this.date_createdField;
            }
            set
            {
                this.date_createdField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string display_name
        {
            get
            {
                return this.display_nameField;
            }
            set
            {
                this.display_nameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string email_address
        {
            get
            {
                return this.email_addressField;
            }
            set
            {
                this.email_addressField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string enc_key
        {
            get
            {
                return this.enc_keyField;
            }
            set
            {
                this.enc_keyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string facebook
        {
            get
            {
                return this.facebookField;
            }
            set
            {
                this.facebookField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string first_name
        {
            get
            {
                return this.first_nameField;
            }
            set
            {
                this.first_nameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string full_name
        {
            get
            {
                return this.full_nameField;
            }
            set
            {
                this.full_nameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int gender_id
        {
            get
            {
                return this.gender_idField;
            }
            set
            {
                this.gender_idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string height
        {
            get
            {
                return this.heightField;
            }
            set
            {
                this.heightField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string image_path
        {
            get
            {
                return this.image_pathField;
            }
            set
            {
                this.image_pathField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string instagram
        {
            get
            {
                return this.instagramField;
            }
            set
            {
                this.instagramField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string last_name
        {
            get
            {
                return this.last_nameField;
            }
            set
            {
                this.last_nameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string linkedin
        {
            get
            {
                return this.linkedinField;
            }
            set
            {
                this.linkedinField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string middle_name
        {
            get
            {
                return this.middle_nameField;
            }
            set
            {
                this.middle_nameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int nationality_id
        {
            get
            {
                return this.nationality_idField;
            }
            set
            {
                this.nationality_idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string nick_name
        {
            get
            {
                return this.nick_nameField;
            }
            set
            {
                this.nick_nameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string perm_city
        {
            get
            {
                return this.perm_cityField;
            }
            set
            {
                this.perm_cityField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string perm_country
        {
            get
            {
                return this.perm_countryField;
            }
            set
            {
                this.perm_countryField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string perm_state
        {
            get
            {
                return this.perm_stateField;
            }
            set
            {
                this.perm_stateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string perm_street
        {
            get
            {
                return this.perm_streetField;
            }
            set
            {
                this.perm_streetField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string perm_zipcode
        {
            get
            {
                return this.perm_zipcodeField;
            }
            set
            {
                this.perm_zipcodeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string phone_fax
        {
            get
            {
                return this.phone_faxField;
            }
            set
            {
                this.phone_faxField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string phone_home
        {
            get
            {
                return this.phone_homeField;
            }
            set
            {
                this.phone_homeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string phone_mobile
        {
            get
            {
                return this.phone_mobileField;
            }
            set
            {
                this.phone_mobileField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string phone_other
        {
            get
            {
                return this.phone_otherField;
            }
            set
            {
                this.phone_otherField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string phone_work
        {
            get
            {
                return this.phone_workField;
            }
            set
            {
                this.phone_workField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int question1
        {
            get
            {
                return this.question1Field;
            }
            set
            {
                this.question1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int question2
        {
            get
            {
                return this.question2Field;
            }
            set
            {
                this.question2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int religion_id
        {
            get
            {
                return this.religion_idField;
            }
            set
            {
                this.religion_idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int salutation_id
        {
            get
            {
                return this.salutation_idField;
            }
            set
            {
                this.salutation_idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string skype
        {
            get
            {
                return this.skypeField;
            }
            set
            {
                this.skypeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string tumblr
        {
            get
            {
                return this.tumblrField;
            }
            set
            {
                this.tumblrField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string twitter
        {
            get
            {
                return this.twitterField;
            }
            set
            {
                this.twitterField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string user_code
        {
            get
            {
                return this.user_codeField;
            }
            set
            {
                this.user_codeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int user_group_id
        {
            get
            {
                return this.user_group_idField;
            }
            set
            {
                this.user_group_idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int user_id
        {
            get
            {
                return this.user_idField;
            }
            set
            {
                this.user_idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string userhash
        {
            get
            {
                return this.userhashField;
            }
            set
            {
                this.userhashField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string username
        {
            get
            {
                return this.usernameField;
            }
            set
            {
                this.usernameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int warehouse_id
        {
            get
            {
                return this.warehouse_idField;
            }
            set
            {
                this.warehouse_idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string website
        {
            get
            {
                return this.websiteField;
            }
            set
            {
                this.websiteField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string weight
        {
            get
            {
                return this.weightField;
            }
            set
            {
                this.weightField = value;
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.Runtime.Serialization.DataContractAttribute(Name="menu_view_restriction_lib", Namespace="http://schemas.datacontract.org/2004/07/BridgeWCF.Library")]
    public partial class menu_view_restriction_lib : object
    {
        
        private string actionField;
        
        private string class_Field;
        
        private int company_idField;
        
        private string controllerField;
        
        private bool duplicateField;
        
        private bool enable_duplicateField;
        
        private bool enable_modifyField;
        
        private bool enable_newField;
        
        private bool enable_others1Field;
        
        private bool enable_others2Field;
        
        private bool enable_others3Field;
        
        private bool enable_others4Field;
        
        private bool enable_others5Field;
        
        private bool enable_printsField;
        
        private int enable_view_allField;
        
        private bool enable_viewsField;
        
        private bool modifyField;
        
        private int module_idField;
        
        private string module_nameField;
        
        private bool module_typeField;
        
        private bool new_Field;
        
        private bool others1Field;
        
        private bool others2Field;
        
        private bool others3Field;
        
        private bool others4Field;
        
        private bool others5Field;
        
        private int parent_module_idField;
        
        private bool printsField;
        
        private int seqnField;
        
        private int user_group_idField;
        
        private int view_allField;
        
        private bool viewsField;
        
        private int warehouse_idField;
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string action
        {
            get
            {
                return this.actionField;
            }
            set
            {
                this.actionField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string class_
        {
            get
            {
                return this.class_Field;
            }
            set
            {
                this.class_Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int company_id
        {
            get
            {
                return this.company_idField;
            }
            set
            {
                this.company_idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string controller
        {
            get
            {
                return this.controllerField;
            }
            set
            {
                this.controllerField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool duplicate
        {
            get
            {
                return this.duplicateField;
            }
            set
            {
                this.duplicateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool enable_duplicate
        {
            get
            {
                return this.enable_duplicateField;
            }
            set
            {
                this.enable_duplicateField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool enable_modify
        {
            get
            {
                return this.enable_modifyField;
            }
            set
            {
                this.enable_modifyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool enable_new
        {
            get
            {
                return this.enable_newField;
            }
            set
            {
                this.enable_newField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool enable_others1
        {
            get
            {
                return this.enable_others1Field;
            }
            set
            {
                this.enable_others1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool enable_others2
        {
            get
            {
                return this.enable_others2Field;
            }
            set
            {
                this.enable_others2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool enable_others3
        {
            get
            {
                return this.enable_others3Field;
            }
            set
            {
                this.enable_others3Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool enable_others4
        {
            get
            {
                return this.enable_others4Field;
            }
            set
            {
                this.enable_others4Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool enable_others5
        {
            get
            {
                return this.enable_others5Field;
            }
            set
            {
                this.enable_others5Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool enable_prints
        {
            get
            {
                return this.enable_printsField;
            }
            set
            {
                this.enable_printsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int enable_view_all
        {
            get
            {
                return this.enable_view_allField;
            }
            set
            {
                this.enable_view_allField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool enable_views
        {
            get
            {
                return this.enable_viewsField;
            }
            set
            {
                this.enable_viewsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool modify
        {
            get
            {
                return this.modifyField;
            }
            set
            {
                this.modifyField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int module_id
        {
            get
            {
                return this.module_idField;
            }
            set
            {
                this.module_idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public string module_name
        {
            get
            {
                return this.module_nameField;
            }
            set
            {
                this.module_nameField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool module_type
        {
            get
            {
                return this.module_typeField;
            }
            set
            {
                this.module_typeField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool new_
        {
            get
            {
                return this.new_Field;
            }
            set
            {
                this.new_Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool others1
        {
            get
            {
                return this.others1Field;
            }
            set
            {
                this.others1Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool others2
        {
            get
            {
                return this.others2Field;
            }
            set
            {
                this.others2Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool others3
        {
            get
            {
                return this.others3Field;
            }
            set
            {
                this.others3Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool others4
        {
            get
            {
                return this.others4Field;
            }
            set
            {
                this.others4Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool others5
        {
            get
            {
                return this.others5Field;
            }
            set
            {
                this.others5Field = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int parent_module_id
        {
            get
            {
                return this.parent_module_idField;
            }
            set
            {
                this.parent_module_idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool prints
        {
            get
            {
                return this.printsField;
            }
            set
            {
                this.printsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int seqn
        {
            get
            {
                return this.seqnField;
            }
            set
            {
                this.seqnField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int user_group_id
        {
            get
            {
                return this.user_group_idField;
            }
            set
            {
                this.user_group_idField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int view_all
        {
            get
            {
                return this.view_allField;
            }
            set
            {
                this.view_allField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public bool views
        {
            get
            {
                return this.viewsField;
            }
            set
            {
                this.viewsField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute()]
        public int warehouse_id
        {
            get
            {
                return this.warehouse_idField;
            }
            set
            {
                this.warehouse_idField = value;
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="wcf_Master.IMaster_Service")]
    public interface IMaster_Service
    {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMaster_Service/user_authenticate", ReplyAction="http://tempuri.org/IMaster_Service/user_authenticateResponse")]
        System.Threading.Tasks.Task<wcf_Master.login_authentication> user_authenticateAsync(string username, string userhash);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMaster_Service/menu_view_restriction", ReplyAction="http://tempuri.org/IMaster_Service/menu_view_restrictionResponse")]
        System.Threading.Tasks.Task<wcf_Master.menu_view_restriction_lib[]> menu_view_restrictionAsync(int user_group_id, int module_id, int company_id, int warehouse_id);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    public interface IMaster_ServiceChannel : wcf_Master.IMaster_Service, System.ServiceModel.IClientChannel
    {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.Tools.ServiceModel.Svcutil", "2.0.1-preview-30310-0943")]
    public partial class Master_ServiceClient : System.ServiceModel.ClientBase<wcf_Master.IMaster_Service>, wcf_Master.IMaster_Service
    {
        
        /// <summary>
        /// Implement this partial method to configure the service endpoint.
        /// </summary>
        /// <param name="serviceEndpoint">The endpoint to configure</param>
        /// <param name="clientCredentials">The client credentials</param>
        static partial void ConfigureEndpoint(System.ServiceModel.Description.ServiceEndpoint serviceEndpoint, System.ServiceModel.Description.ClientCredentials clientCredentials);
        
        public Master_ServiceClient() : 
                base(Master_ServiceClient.GetDefaultBinding(), Master_ServiceClient.GetDefaultEndpointAddress())
        {
            this.Endpoint.Name = EndpointConfiguration.BasicHttpBinding_IMaster_Service.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Master_ServiceClient(EndpointConfiguration endpointConfiguration) : 
                base(Master_ServiceClient.GetBindingForEndpoint(endpointConfiguration), Master_ServiceClient.GetEndpointAddress(endpointConfiguration))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Master_ServiceClient(EndpointConfiguration endpointConfiguration, string remoteAddress) : 
                base(Master_ServiceClient.GetBindingForEndpoint(endpointConfiguration), new System.ServiceModel.EndpointAddress(remoteAddress))
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Master_ServiceClient(EndpointConfiguration endpointConfiguration, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(Master_ServiceClient.GetBindingForEndpoint(endpointConfiguration), remoteAddress)
        {
            this.Endpoint.Name = endpointConfiguration.ToString();
            ConfigureEndpoint(this.Endpoint, this.ClientCredentials);
        }
        
        public Master_ServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress)
        {
        }
        
        public System.Threading.Tasks.Task<wcf_Master.login_authentication> user_authenticateAsync(string username, string userhash)
        {
            return base.Channel.user_authenticateAsync(username, userhash);
        }
        
        public System.Threading.Tasks.Task<wcf_Master.menu_view_restriction_lib[]> menu_view_restrictionAsync(int user_group_id, int module_id, int company_id, int warehouse_id)
        {
            return base.Channel.menu_view_restrictionAsync(user_group_id, module_id, company_id, warehouse_id);
        }
        
        public virtual System.Threading.Tasks.Task OpenAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginOpen(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndOpen));
        }
        
        public virtual System.Threading.Tasks.Task CloseAsync()
        {
            return System.Threading.Tasks.Task.Factory.FromAsync(((System.ServiceModel.ICommunicationObject)(this)).BeginClose(null, null), new System.Action<System.IAsyncResult>(((System.ServiceModel.ICommunicationObject)(this)).EndClose));
        }
        
        private static System.ServiceModel.Channels.Binding GetBindingForEndpoint(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IMaster_Service))
            {
                System.ServiceModel.BasicHttpBinding result = new System.ServiceModel.BasicHttpBinding();
                result.MaxBufferSize = int.MaxValue;
                result.ReaderQuotas = System.Xml.XmlDictionaryReaderQuotas.Max;
                result.MaxReceivedMessageSize = int.MaxValue;
                result.AllowCookies = true;
                return result;
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.EndpointAddress GetEndpointAddress(EndpointConfiguration endpointConfiguration)
        {
            if ((endpointConfiguration == EndpointConfiguration.BasicHttpBinding_IMaster_Service))
            {
                return new System.ServiceModel.EndpointAddress("http://localhost:2001/Master_Service.svc");
            }
            throw new System.InvalidOperationException(string.Format("Could not find endpoint with name \'{0}\'.", endpointConfiguration));
        }
        
        private static System.ServiceModel.Channels.Binding GetDefaultBinding()
        {
            return Master_ServiceClient.GetBindingForEndpoint(EndpointConfiguration.BasicHttpBinding_IMaster_Service);
        }
        
        private static System.ServiceModel.EndpointAddress GetDefaultEndpointAddress()
        {
            return Master_ServiceClient.GetEndpointAddress(EndpointConfiguration.BasicHttpBinding_IMaster_Service);
        }
        
        public enum EndpointConfiguration
        {
            
            BasicHttpBinding_IMaster_Service,
        }
    }
}
